M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date Di 26 Mär 2024 17:41:38
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-26T17:41:38+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.600
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T3C1.200
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C1.300
%
G90
G05
T1
X140.5Y-91.0
X142.0Y-96.0
T2
X161.3Y-94.5
X164.7Y-94.5
T3
X159.0Y-89.0
X159.0Y-100.0
X166.5Y-89.0
X166.5Y-100.0
T4
X135.5Y-91.0
X135.5Y-94.5
X135.5Y-98.0
M30
